---
title: "Boxplot_OOB"
output: html_document
date: "2023-08-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

```{r}
#Load dataframe
temp_oob_train <- read.delim("/Users/stella/RF Loop Results/training_contingency.txt", sep = " ", header = T)
temp_oob_test <- read.delim("/Users/stella/RF Loop Results/testing_contingency.txt", sep = " ", header = T)

temp <- data.frame(meanErr = c(temp_oob_train$MeanErr,temp_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
temp$type <- as.character(temp$type)
temp$type <- as.factor(temp$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = temp, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Temp at 37")
```

```{r}
#Load dataframe
resistance_1_oob_train <- read.delim("/Users/stella/resistance/X_FC_resistance/training_contingency_resistance_1.txt", sep = " ", header = T)
resistance_1_oob_test <- read.delim("/Users/stella/resistance/X_FC_resistance/testing_contingency_resistance_1.txt", sep = " ", header = T)

r1 <- data.frame(meanErr = c(resistance_1_oob_train$MeanErr,resistance_1_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r1$type <- as.character(r1$type)
r1$type <- as.factor(r1$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r1, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "X_FC_resistance")
```

```{r}
#Load dataframe
resistance_2_oob_train <- read.delim("/Users/stella/resistance/Fluconazole_resistance/training_contingency_resistance_2.txt", sep = " ", header = T)
resistance_2_oob_test <- read.delim("/Users/stella/resistance/Fluconazole_resistance/testing_contingency_resistance_2.txt", sep = " ", header = T)

r2 <- data.frame(meanErr = c(resistance_2_oob_train$MeanErr,resistance_2_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r2$type <- as.character(r2$type)
r2$type <- as.factor(r2$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r2, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Fluconazole_resistance")
```


```{r}
#Load dataframe
resistance_3_oob_train <- read.delim("/Users/stella/resistance/Itraconazole_resistance/training_contingency_resistance_3.txt", sep = " ", header = T)
resistance_3_oob_test <- read.delim("/Users/stella/resistance/Itraconazole_resistance/testing_contingency_resistance_3.txt", sep = " ", header = T)

r3 <- data.frame(meanErr = c(resistance_3_oob_train$MeanErr,resistance_3_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r3$type <- as.character(r3$type)
r3$type <- as.factor(r3$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r3, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Itraconazole_resistance")
```

```{r}
#Load dataframe
resistance_4_oob_train <- read.delim("/Users/stella/resistance/Voriconazole_resistance/training_contingency_resistance_4.txt", sep = " ", header = T)
resistance_4_oob_test <- read.delim("/Users/stella/resistance/Voriconazole_resistance/testing_contingency_resistance_4.txt", sep = " ", header = T)

r4 <- data.frame(meanErr = c(resistance_4_oob_train$MeanErr,resistance_4_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r4$type <- as.character(r4$type)
r4$type <- as.factor(r4$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r4, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Voriconazole_resistance")
```

```{r}
#Load dataframe
resistance_5_oob_train <- read.delim("/Users/stella/resistance/Posaconazole_resistance/training_contingency_resistance_5.txt", sep = " ", header = T)
resistance_5_oob_test <- read.delim("/Users/stella/resistance/Posaconazole_resistance/testing_contingency_resistance_5.txt", sep = " ", header = T)

r5 <- data.frame(meanErr = c(resistance_5_oob_train$MeanErr,resistance_5_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r5$type <- as.character(r5$type)
r5$type <- as.factor(r5$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r5, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Posaconazole_resistance")
```



```{r}
#Load dataframe
resistance_6_oob_train <- read.delim("/Users/stella/resistance/Terbinafin_resistance/training_contingency_resistance_6.txt", sep = " ", header = T)
resistance_6_oob_test <- read.delim("/Users/stella/resistance/Terbinafin_resistance/testing_contingency_resistance_6.txt", sep = " ", header = T)

r6 <- data.frame(meanErr = c(resistance_6_oob_train$MeanErr,resistance_6_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r6$type <- as.character(r6$type)
r6$type <- as.factor(r6$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r6, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Terbinafin_resistance")
```

```{r}
resistance_7_oob_train <- read.delim("/Users/stella/resistance/Caspofungi_resistance/training_contingency_resistance_7.txt", sep = " ", header = T)
resistance_7_oob_test <- read.delim("/Users/stella/resistance/Caspofungi_resistance/testing_contingency_resistance_7.txt", sep = " ", header = T)

r7 <- data.frame(meanErr = c(resistance_7_oob_train$MeanErr,resistance_7_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r7$type <- as.character(r7$type)
r7$type <- as.factor(r7$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r7, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Caspofungi_resistance")
```

```{r}
resistance_8_oob_train <- read.delim("/Users/stella/resistance/Amphotericin_B_resistance/training_contingency_resistance_8.txt", sep = " ", header = T)
resistance_8_oob_test <- read.delim("/Users/stella/resistance/Amphotericin_B_resistance/testing_contingency_resistance_8.txt", sep = " ", header = T)

r8 <- data.frame(meanErr = c(resistance_8_oob_train$MeanErr,resistance_8_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r8$type <- as.character(r8$type)
r8$type <- as.factor(r8$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r8, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Amphotericin_B_resistance")
```

```{r}
resistance_9_oob_train <- read.delim("/Users/stella/resistance/Resistance_to_azoles/training_contingency_resistance_9.txt", sep = " ", header = T)
resistance_9_oob_test <- read.delim("/Users/stella/resistance/Resistance_to_azoles/training_contingency_resistance_9.txt", sep = " ", header = T)

r9 <- data.frame(meanErr = c(resistance_9_oob_train$MeanErr,resistance_9_oob_test$MeanErr),type = c(rep("train", 100),rep("test",100)))

#Set type as factor
r9$type <- as.character(r9$type)
r9$type <- as.factor(r9$type)

#boxplot(temp_oob$train_MeanErr,temp_oob$test_MeanErr, names = c("train oob", "test oob"))
ggplot(data = r9, mapping = aes(x = type , y = meanErr)) + geom_boxplot() + labs(title = "Resistance_to_azoles")
```
